name: ackman678
description: science and software by James Ackman
owner: ackman678

url: http://github.com/ackman678

#paginate: 10


markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


#permalink: pretty
pygments: true
